// <auto-generated />
using System;
using ASM_01.DataAccessLayer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_01.DataAccessLayer.Migrations
{
    [DbContext(typeof(EVRetailsDbContext))]
    [Migration("20250923114140_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.EvModel", b =>
                {
                    b.Property<int>("EvModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvModelId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EvModelId");

                    b.ToTable("EvModel", (string)null);
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.EvTrim", b =>
                {
                    b.Property<int>("EvTrimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvTrimId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EvModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("TrimName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EvTrimId");

                    b.HasIndex("EvModelId");

                    b.ToTable("EvTrim", (string)null);
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.Spec", b =>
                {
                    b.Property<int>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpecId");

                    b.HasIndex("SpecName")
                        .IsUnique();

                    b.ToTable("Spec", (string)null);
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.TrimPrice", b =>
                {
                    b.Property<int>("TrimPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrimPriceId"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvTrimId")
                        .HasColumnType("int");

                    b.Property<decimal>("ListedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TrimPriceId");

                    b.HasIndex("EvTrimId");

                    b.ToTable("TrimPrice", (string)null);
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.TrimSpec", b =>
                {
                    b.Property<int>("EvTrimId")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EvTrimId", "SpecId");

                    b.HasIndex("SpecId");

                    b.ToTable("TrimSpec", (string)null);
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.EvTrim", b =>
                {
                    b.HasOne("ASM_01.DataAccessLayer.Entities.EvModel", "EvModel")
                        .WithMany("Trims")
                        .HasForeignKey("EvModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvModel");
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.TrimPrice", b =>
                {
                    b.HasOne("ASM_01.DataAccessLayer.Entities.EvTrim", "EvTrim")
                        .WithMany("Prices")
                        .HasForeignKey("EvTrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvTrim");
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.TrimSpec", b =>
                {
                    b.HasOne("ASM_01.DataAccessLayer.Entities.EvTrim", "EvTrim")
                        .WithMany("TrimSpecs")
                        .HasForeignKey("EvTrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM_01.DataAccessLayer.Entities.Spec", "Spec")
                        .WithMany("TrimSpecs")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvTrim");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.EvModel", b =>
                {
                    b.Navigation("Trims");
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.EvTrim", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("TrimSpecs");
                });

            modelBuilder.Entity("ASM_01.DataAccessLayer.Entities.Spec", b =>
                {
                    b.Navigation("TrimSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
